CREATE OR REPLACE TABLE Users
(
    Id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Username VARCHAR(320) NOT NULL,
    CONSTRAINT `UX_User_Username` UNIQUE (Username),
    HashedPassword VARCHAR(40) NOT NULL, -- SHA1
    AddBy INT NOT NULL,
    AddDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
